services:

  db:
    container_name: logcenter_db
    image: "postgres:18"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    shm_size: '256m' # Necessary to use Postgres VACUUM. You can increment it as you need
    volumes:
      - ./data/db/:/var/lib/postgresql/data/

  server:
    container_name: logcenter_server
    build: ./src/server
    image: hudsonventura/logcenter_server:latest
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_LISTEN: http://0.0.0.0:9200
      JWT_KEY: ${JWT_KEY}
    depends_on:
      - db
    ports:
      - ${LOGCENTER_API_PORT}:9200

  client:
    container_name: logcenter_client
    build: ./src/client
    image: hudsonventura/logcenter_client:latest
    restart: always
    ports:
      - ${LOGCENTER_INTERFACE_PORT}:80
    depends_on:
      - server
