//ListTables
GET {{VITE_API_HOST}}/ListTables

HTTP/1.1 200  - OK
server: openresty
date: Sun, 10 Nov 2024 00:17:03 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
connection: keep-alive
x-served-by: logcenter.hudsonventura.ddnsgeek.com
###
//Search
GET {{VITE_API_HOST}}/testekkk
?datetime1=2024-11-02T04:00:00.000Z
&datetime2=2024-11-04T01:43:12.089Z
&timezone=America/Sao_Paulo

HTTP/1.1 200  - OK
server: openresty
date: Sun, 10 Nov 2024 00:16:55 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
connection: keep-alive
x-served-by: logcenter.hudsonventura.ddnsgeek.com
###
//Get one object
GET {{VITE_API_HOST}}/{{table}}/7258874717069639680